#!/bin/bash

CASE_NAME="PR4Conv"
CASE_DIR_NAME="pr4"

ROT_1x1="True"
ROT_1x1_NAME='w'

NOISE_VAR="0.01"
NOISE_VAR_NAME='n01'

OUTPUT_MAIN="/ws/output/"

TRAIN_ROTS="0 15 45 90 180"
TEST_ROTS="0 15 45 90 180"

MODEL_TYPE="PSR"

PSR_CONV_ARGS="MODEL.CUSTOM.${MODEL_TYPE}.CONVF_NAME \"${CASE_NAME}F\" MODEL.CUSTOM.${MODEL_TYPE}.CONV_NAME ${CASE_NAME}"

PR_CONV_ARGS="MODEL.CUSTOM.${MODEL_TYPE}.CONV_NAME ${CASE_NAME}"

BACKBONE_NAME="build_psr_backbone"

INPUT_SIZE="32"

for TRAIN_ROT in ${TRAIN_ROTS}; do
  for TEST_ROT in ${TEST_ROTS}; do
    OUTPUT_LOG="${OUTPUT_MAIN}${CASE_DIR_NAME}_${ROT_1x1_NAME}_${NOISE_VAR_NAME}_c20/${CASE_DIR_NAME}_${ROT_1x1_NAME}_${NOISE_VAR_NAME}_c20_${TRAIN_ROT}_${TEST_ROT}"

    python classification_train_net.py\
         ${PSR_CONV_ARGS}\
         MODEL.CUSTOM.${MODEL_TYPE}.ROT_1x1 ${ROT_1x1}\
         MODEL.CUSTOM.${MODEL_TYPE}.NOISE_VAR ${NOISE_VAR}\
         OUTPUT_DIR ${OUTPUT_LOG} \
         DATASETS.CUSTOM.ROTATION_TRAIN ${TRAIN_ROT} DATASETS.CUSTOM.ROTATION_TEST ${TEST_ROT} \
	 MODEL.BACKBONE.NAME ${BACKBONE_NAME}\
	 MODEL.CUSTOM.INPUT_SIZE ${INPUT_SIZE}
  done
done
