MODEL:
  PIXEL_MEAN: [103.530, 116.280, 123.675]
  PIXEL_STD: [57.375, 57.120, 58.395]
  META_ARCHITECTURE: "CustomizedRCNN"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
    FREEZE_AT: 0
  MASK_ON: False
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    DEPTH: 50
    STRIDE_IN_1X1: False
    RES2_OUT_CHANNELS: 256
    STEM_OUT_CHANNELS: 64
    NORM: "GN"
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "CustomizedRRPN"
  ANCHOR_GENERATOR:
    NAME: "RotatedAnchorGenerator"
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
    ANGLES: [[-90, -60, -30, 0, 30, 60, 90]]
  RPN:
    HEAD_NAME: 'CustomizedRPNHead'
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 500  # Per FPN level
    PRE_NMS_TOPK_TEST: 500  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 500
    POST_NMS_TOPK_TEST: 500
    BBOX_REG_WEIGHTS: (2.0, 2.0, 1.0, 1.0, 2.0)
    IOU_THRESHOLDS: [0.3, 0.7]
    SMOOTH_L1_BETA: 1.5
  ROI_HEADS:
    NAME: 'CascadeRROIHeads'
    NUM_CLASSES: 4
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    IOU_THRESHOLDS: [0.4]
    NMS_THRESH_TEST: 0.4
    SCORE_THRESH_TEST: 0.3
    BATCH_SIZE_PER_IMAGE: 512
  ROI_BOX_HEAD:
    NAME: "CustomFastRCNNConvFCHead"
    NUM_FC: 3
    POOLER_RESOLUTION: 8
    POOLER_TYPE: "ROIAlignRotated"
    BBOX_REG_WEIGHTS: (10.0, 10.0, 5.0, 5.0, 10.0)
    CLS_AGNOSTIC_BBOX_REG: True
    SMOOTH_L1_BETA: 1.5
#    NORM: "GN"
  ROI_BOX_CASCADE_HEAD:
    BBOX_REG_WEIGHTS: ((10.0, 10.0, 5.0, 5.0, 10.0), (20.0, 20.0, 10.0, 10.0, 20.0), (30.0, 30.0, 15.0, 15.0, 30.0),)
    IOUS: (0.4, 0.5, 0.6)
DATASETS:
  CUSTOM:
    DATASET_MAPPER: "TrainDatasetMapperRotated"
  TRAIN: ("dota_rotated_train_coco",)
  TEST: ()
DATALOADER:
  NUM_WORKERS: 2
SOLVER:
  CHECKPOINT_PERIOD: 3000
  IMS_PER_BATCH: 2
  BASE_LR: 0.001
  STEPS: (30000, 60000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768)
#  CROP:
#    ENABLED: True
VERSION: 2
