_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
    FREEZE_AT: 1
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
#  WEIGHTS: "catalog://ImageNetPretrained/FAIR/X-152-32x8d-IN5k"
#  WEIGHTS: "catalog://ImageNetPretrained/FAIR/R-101-GN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
#    NUM_GROUPS: 32
#    WIDTH_PER_GROUP: 8
    DEPTH: 101
    DEFORM_ON_PER_STAGE: [False, True, True, True]
    NORM: "BN"
  RPN:
    BATCH_SIZE_PER_IMAGE: 256
  CUSTOM:
    FOCAL_LOSS_GAMMA: 2.0
    FOCAL_LOSS_ALPHA: 0.25
    FPN:
      CONVF_NAME: "PR4ConvF"
      NOISE_VAR: 0.0
    BRANCH:
      NUM_BRANCH: 4
  PROPOSAL_GENERATOR:
    NAME: "RRPN"
  ROI_HEADS:
    NAME: 'RROIHeads'
    NUM_CLASSES: 4
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    IOU_THRESHOLDS: [0.6]
    NMS_THRESH_TEST: 0.4
    SCORE_THRESH_TEST: 0.4
    BATCH_SIZE_PER_IMAGE: 512
    PROPOSAL_APPEND_GT: False
DATASETS:
  CUSTOM:
    DATASET_MAPPER: "TrainDatasetMapperRotated"
  TRAIN: ("dacon_rotated_all_coco",)
  TEST: ("dacon_rotated_val_coco",)
DATALOADER:
  NUM_WORKERS: 3
SOLVER:
  CHECKPOINT_PERIOD: 3000
  IMS_PER_BATCH: 6
  BASE_LR: 0.001
  STEPS: (60000, 90000)
  MAX_ITER: 150000
TEST:
  EVAL_PERIOD: 10000
INPUT:
  MIN_SIZE_TRAIN: (440, 472, 504, 636, 668)
#  CROP:
#    ENABLED: True
VERSION: 2
VIS_PERIOD: 1000
OUTPUT_DIR: "/ws/output/detection/r_fair_normal"
#OUTPUT_DIR: "/ws/output/detection/proposal"
